rewritten to support script install of ovos on Pi
OpenVoiceOS/community-docs pull request #66
Opened 2023-06-20 20:54 UTC by Bulwagga

@builderjer I have created a new draft of the instructions for creating a scripted OVOS build on a RPi system.  Please feel free to change anything to your liking.
 
I notice the link to the pre-built images is dead.  Where are they now?  I edited the instructions for installing the images but I'm not sure about their status.

I believe I handled the model questions correctly in mycroft.conf.

Any reason why we couldn't put this headless system on an RPi 4?

Thank you

2023-06-20 21:49 UTC, builderjer commented
We are working on a dedicated image server, but AFAK we do not have a permanent one yet. I may just set up a FTP server to do so, just haven't done so yet.

There is absolutely NO reason this should not ork on a pi4. In fact, it would probably work better

2023-06-21 00:00 UTC, builderjer requested changes
Couple of thoughts, main one being the download link.  Figure out something there, and I think this is good

2023-06-21 01:04 UTC, Bulwagga commented on docs/install_raspbian.md
> +Download a pre-built OVOS/PI image from [dead link: OpenVoiceOS Downloads Site](https://downloads.openvoiceos.com/images/raspbian/).
Sir!  I would NEVER put dead link in the published document. Sorry to scare you.  I will update to reference the image server.

2023-06-21 04:33 UTC, builderjer approved these changes

2023-06-21 04:34 UTC, merged

2023-06-21 13:43 UTC, Bulwagga commented on docs/install_raspbian.md
> +#### Method 1: Tried, tested, and reliable, but not a headless install
Got it. Wording could be way better.  Both methods result in a headless system. Method 1  requires a monitor attached to the Pi in order to complete the install. Method 2 doesn't require a monitor in order to complete the install.  Let me give you another iteration on the headers.